[package]
name = "procss-xtest"
version = "0.1.8"
edition = "2021"

[[bin]]
name = "xtest"
path = "main.rs"
bench = false

[dependencies]
grcov = { workspace = true }
once_cell = { workspace = true }
procss-utils = { path = "../utils" }
regex = { workspace = true }
